# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Chuxwa"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Point Cloud Representation Learning":
        filters: ["Point Cloud Representation", "Point Cloud Understanding", "Point Cloud Analysis", 
                  "3D Representation Learning", "3D Understanding",
                  "3D Pre-trained", "Pre-trained Point Cloud", "Point Cloud Pre-trained"]
    "Point Cloud Object Detection":
        filters: ["3D Object Detection", "Point Cloud Object Detection", 
                  "3D Instance Detection", "3D Object Localization", "Point Cloud Instance Detection"]
    "Point Cloud Segmentation":
        filters: ["Point Cloud Segmentation", "3D Segmentation", 
                  "Point Cloud Semantic Segmentation", "Point Cloud Instance Segmentation", 
                  "3D Semantic Segmentation", "3D Instance Segmentation", 
                  "Point Cloud Scene Understanding", "3D Scene Understanding"]
